[package]
name = "odt_to_md"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zip = "0.6.4"
xml-rs = "0.8.4"

[dev-dependencies]
difference = "2.0.0"